[package]
name = "caternary"
version = "0.1.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2024"
description = "Caternary is a stack-based language and runtime."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[dependencies]
