[package]
name = "one_two_eight"
version = "0.7.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "one_two_eight provides typed 128-bit identifiers."
license = "Apache-2.0"
repository = "https://github.com/rescrv/blue"

[features]
default = ["generate_id_prototk"]
generate_id_prototk = ["buffertk", "prototk"]

[dependencies]
buffertk = { path = "../buffertk", version = "0.11", optional = true }
prototk = { path = "../prototk", version = "0.11", optional = true }
